<?xml version="1.0" encoding="UTF-8" ?>
		<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
		<channel>
			<title>Prague Race</title>
			<atom:link href="http://www.praguerace.com/rss.php" rel="self" type="application/rss+xml" />
			<link>http://www.praguerace.com/</link>
			<description>Latest Prague Race comics and news</description>
			<language>en-us</language><item><title><![CDATA[Prague Race - 303]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/303">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/303</link><author>tech@thehiveworks.com</author><pubDate>Mon, 10 Apr 2017 13:09:00 -0400</pubDate><guid>http://www.praguerace.com/comic/303</guid></item><item><title><![CDATA[Prague Race - 302]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/302">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/302</link><author>tech@thehiveworks.com</author><pubDate>Thu, 06 Apr 2017 11:28:00 -0400</pubDate><guid>http://www.praguerace.com/comic/302</guid></item><item><title><![CDATA[Prague Race - 301]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/301">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/301</link><author>tech@thehiveworks.com</author><pubDate>Fri, 31 Mar 2017 14:22:00 -0400</pubDate><guid>http://www.praguerace.com/comic/301</guid></item><item><title><![CDATA[Prague Race - 300]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/300">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/300</link><author>tech@thehiveworks.com</author><pubDate>Mon, 27 Mar 2017 16:05:00 -0400</pubDate><guid>http://www.praguerace.com/comic/300</guid></item><item><title><![CDATA[Prague Race - 06]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/06">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/06</link><author>tech@thehiveworks.com</author><pubDate>Thu, 23 Feb 2017 06:03:00 -0500</pubDate><guid>http://www.praguerace.com/comic/06</guid></item><item><title><![CDATA[Prague Race - 05]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/05">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/05</link><author>tech@thehiveworks.com</author><pubDate>Mon, 20 Feb 2017 06:03:00 -0500</pubDate><guid>http://www.praguerace.com/comic/05</guid></item><item><title><![CDATA[Prague Race - 04]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/04">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/04</link><author>tech@thehiveworks.com</author><pubDate>Thu, 16 Feb 2017 06:02:00 -0500</pubDate><guid>http://www.praguerace.com/comic/04</guid></item><item><title><![CDATA[Prague Race - 03]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/03">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/03</link><author>tech@thehiveworks.com</author><pubDate>Mon, 13 Feb 2017 06:02:00 -0500</pubDate><guid>http://www.praguerace.com/comic/03</guid></item><item><title><![CDATA[Prague Race - 02]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/02">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/02</link><author>tech@thehiveworks.com</author><pubDate>Thu, 09 Feb 2017 06:01:00 -0500</pubDate><guid>http://www.praguerace.com/comic/02</guid></item><item><title><![CDATA[Prague Race - 01]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/01">New comic!</a><br>Today's News:<br><p>Here you go, finally!</p>
<p>I've put all the pages here on queue, hopefully it works!</p>
]]></description><link>http://www.praguerace.com/comic/01</link><author>tech@thehiveworks.com</author><pubDate>Mon, 06 Feb 2017 06:00:00 -0500</pubDate><guid>http://www.praguerace.com/comic/01</guid></item><item><title><![CDATA[Prague Race - 24COMIC_21]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic21">New comic!</a><br>Today's News:<br><p>PHEW AND THERE YOU GO!</p>
<p>Prague Race will return on 1.2, so that's ABOUT ONE WEEK FROM NOW!</p>
<p>It will be updating on mondays and thursdays, and sometimes I might post a third page whenever I have the energy to draw more.&nbsp;</p>
<p>So many new shiny pages waiting to be uploaded...&nbsp;<a href="https://www.patreon.com/praguerace">Patrons will find the whole buffer soon from my patreon!</a></p>
<p><img src="https%3A//pbs.twimg.com/media/C3SgoVdWAAEYVSn.jpg%3Alarge" alt="" width="515" height="686"></p>
]]></description><link>http://www.praguerace.com/comic/24comic21</link><author>tech@thehiveworks.com</author><pubDate>Mon, 30 Jan 2017 08:09:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic21</guid></item><item><title><![CDATA[Prague Race - 24COMIC_20]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic20">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/24comic20</link><author>tech@thehiveworks.com</author><pubDate>Mon, 30 Jan 2017 08:08:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic20</guid></item><item><title><![CDATA[Prague Race - 24COMIC_19]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic19">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/24comic19</link><author>tech@thehiveworks.com</author><pubDate>Sun, 29 Jan 2017 05:27:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic19</guid></item><item><title><![CDATA[Prague Race - 24COMIC_18]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic18">New comic!</a><br>Today's News:<br><p>At this point it was around 4am, I had been drawing for almost 20 hours, i'm dying,&nbsp;</p>
]]></description><link>http://www.praguerace.com/comic/24comic18</link><author>tech@thehiveworks.com</author><pubDate>Sat, 28 Jan 2017 13:55:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic18</guid></item><item><title><![CDATA[Prague Race - 24COMIC_17]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic17">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/24comic17</link><author>tech@thehiveworks.com</author><pubDate>Fri, 27 Jan 2017 06:12:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic17</guid></item><item><title><![CDATA[Prague Race - 24COMIC_16]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic16">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/24comic16</link><author>tech@thehiveworks.com</author><pubDate>Thu, 26 Jan 2017 15:44:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic16</guid></item><item><title><![CDATA[Prague Race - 24comic_15]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic15">New comic!</a><br>Today's News:<br><p>im doing it. .. im trying. .. my best.. to finish this comic... aaaa......</p>
]]></description><link>http://www.praguerace.com/comic/24comic15</link><author>tech@thehiveworks.com</author><pubDate>Thu, 26 Jan 2017 15:39:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic15</guid></item><item><title><![CDATA[Prague Race - 24COMIC_14]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic14">New comic!</a><br>Today's News:<br>
]]></description><link>http://www.praguerace.com/comic/24comic14</link><author>tech@thehiveworks.com</author><pubDate>Sat, 17 Dec 2016 12:47:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic14</guid></item><item><title><![CDATA[Prague Race - 24COMIC_13]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic13">New comic!</a><br>Today's News:<br><p>OH MY GOD I FORGOT TO UPDATE LOL WHAT THE FUUCK</p>
]]></description><link>http://www.praguerace.com/comic/24comic13</link><author>tech@thehiveworks.com</author><pubDate>Sat, 17 Dec 2016 12:46:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic13</guid></item><item><title><![CDATA[Prague Race - 24COMIC_12]]></title><description><![CDATA[<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<a href="http://www.praguerace.com/comic/24comic12">New comic!</a><br>Today's News:<br><p>At this part you can tell i'm starting to lose it lol</p>
]]></description><link>http://www.praguerace.com/comic/24comic12</link><author>tech@thehiveworks.com</author><pubDate>Mon, 12 Dec 2016 10:34:00 -0500</pubDate><guid>http://www.praguerace.com/comic/24comic12</guid></item></channel></rss>